// tslint:disable
/**
 * 营销通
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AttachmentDto
 */
export interface AttachmentDto {
    /**
     * Semantic64<\"attachment\">，The 64-bit hexadecimal string identifier
     * @type {string}
     * @memberof AttachmentDto
     */
    attachment_id: string;
    /**
     * 
     * @type {string}
     * @memberof AttachmentDto
     */
    attachment_name: string;
}


