// tslint:disable
/**
 * 营销通
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BusinessGetter
 */
export interface BusinessGetter {
    /**
     * The current page number
     * @type {number}
     * @memberof BusinessGetter
     */
    page: number;
    /**
     * The number of items per page
     * @type {number}
     * @memberof BusinessGetter
     */
    size: number;
    /**
     * 
     * @type {number}
     * @memberof BusinessGetter
     */
    service_type?: number;
    /**
     * 
     * @type {number}
     * @memberof BusinessGetter
     */
    review_status?: number;
    /**
     * 
     * @type {boolean}
     * @memberof BusinessGetter
     */
    is_hot?: boolean;
}


