// tslint:disable
/**
 * 营销通
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { BusinessStatus } from './business-status';
import { BusinessType } from './business-type';

/**
 * 
 * @export
 * @interface BusinessQuery
 */
export interface BusinessQuery {
    /**
     * The current page number
     * @type {number}
     * @memberof BusinessQuery
     */
    page: number;
    /**
     * The number of items per page
     * @type {number}
     * @memberof BusinessQuery
     */
    size: number;
    /**
     * 
     * @type {BusinessType}
     * @memberof BusinessQuery
     */
    business_type?: BusinessType;
    /**
     * 
     * @type {BusinessStatus}
     * @memberof BusinessQuery
     */
    business_status?: BusinessStatus;
    /**
     * 
     * @type {boolean}
     * @memberof BusinessQuery
     */
    is_hot?: boolean;
}


