// tslint:disable
/**
 * 营销通
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { BusinessStatus } from './business-status';
import { BusinessType } from './business-type';

/**
 * 
 * @export
 * @interface BusinessItem
 */
export interface BusinessItem {
    /**
     * 
     * @type {number}
     * @memberof BusinessItem
     */
    business_id: number;
    /**
     * 
     * @type {BusinessType}
     * @memberof BusinessItem
     */
    business_type: BusinessType;
    /**
     * 
     * @type {BusinessStatus}
     * @memberof BusinessItem
     */
    business_status: BusinessStatus;
}


