// tslint:disable
/**
 * 营销通
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { BusinessStatus } from './business-status';
import { BusinessType } from './business-type';

/**
 * 
 * @export
 * @interface BusinessSetter
 */
export interface BusinessSetter {
    /**
     * 
     * @type {Array<string>}
     * @memberof BusinessSetter
     */
    business?: Array<string>;
    /**
     * 
     * @type {BusinessType}
     * @memberof BusinessSetter
     */
    business_type?: BusinessType;
    /**
     * 
     * @type {BusinessStatus}
     * @memberof BusinessSetter
     */
    verify_status?: BusinessStatus;
    /**
     * 
     * @type {boolean}
     * @memberof BusinessSetter
     */
    is_hot?: boolean;
}


