// tslint:disable
/**
 * 营销通
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DictData
 */
export interface DictData {
    /**
     * 
     * @type {number}
     * @memberof DictData
     */
    detail_id: number;
    /**
     * 
     * @type {number}
     * @memberof DictData
     */
    label: number;
    /**
     * 
     * @type {string}
     * @memberof DictData
     */
    value: string;
    /**
     * 
     * @type {number}
     * @memberof DictData
     */
    sort?: number;
    /**
     * 
     * @type {number}
     * @memberof DictData
     */
    dict_id?: number;
    /**
     * 
     * @type {string}
     * @memberof DictData
     */
    create_time?: string;
}


