// tslint:disable
/**
 * 营销通
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MessageData
 */
export interface MessageData {
    /**
     * 
     * @type {number}
     * @memberof MessageData
     */
    message_id: number;
    /**
     * 
     * @type {number}
     * @memberof MessageData
     */
    message_type: number;
    /**
     * 
     * @type {string}
     * @memberof MessageData
     */
    message_name: string;
    /**
     * 
     * @type {string}
     * @memberof MessageData
     */
    message_content: string;
    /**
     * 
     * @type {string}
     * @memberof MessageData
     */
    message_url: string;
    /**
     * 
     * @type {boolean}
     * @memberof MessageData
     */
    is_send: boolean;
    /**
     * 
     * @type {string}
     * @memberof MessageData
     */
    send_time?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MessageData
     */
    send_flag?: boolean;
    /**
     * 
     * @type {number}
     * @memberof MessageData
     */
    receive_user?: number;
    /**
     * 
     * @type {string}
     * @memberof MessageData
     */
    created_by?: string;
    /**
     * 
     * @type {string}
     * @memberof MessageData
     */
    updated_by?: string;
    /**
     * 
     * @type {number}
     * @memberof MessageData
     */
    push_number: number;
    /**
     * 
     * @type {number}
     * @memberof MessageData
     */
    click_number: number;
    /**
     * 
     * @type {number}
     * @memberof MessageData
     */
    link_number: number;
    /**
     * 
     * @type {number}
     * @memberof MessageData
     */
    flag: number;
    /**
     * 
     * @type {number}
     * @memberof MessageData
     */
    dtype: number;
}


