// tslint:disable
/**
 * 营销通
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PasswordLogin
 */
export interface PasswordLogin {
    /**
     * 
     * @type {string}
     * @memberof PasswordLogin
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof PasswordLogin
     */
    password: string;
    /**
     * 
     * @type {boolean}
     * @memberof PasswordLogin
     */
    grant_super?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PasswordLogin
     */
    grant_admin?: boolean;
    /**
     * Semantic64<\"user\">，The 64-bit hexadecimal string identifier
     * @type {string}
     * @memberof PasswordLogin
     */
    promotion_user?: string;
    /**
     * 
     * @type {string}
     * @memberof PasswordLogin
     */
    promotion_code?: string;
}


