// tslint:disable
/**
 * 营销通
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PasswordReset
 */
export interface PasswordReset {
    /**
     * Semantic64<\"user\">，The 64-bit hexadecimal string identifier
     * @type {string}
     * @memberof PasswordReset
     */
    user_id: string;
    /**
     * 
     * @type {string}
     * @memberof PasswordReset
     */
    old?: string;
    /**
     * 
     * @type {string}
     * @memberof PasswordReset
     */
    _new: string;
}


