// tslint:disable
/**
 * 营销通
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ServiceSetter
 */
export interface ServiceSetter {
    /**
     * 
     * @type {Array<string>}
     * @memberof ServiceSetter
     */
    id_list: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof ServiceSetter
     */
    service_type?: number;
    /**
     * 
     * @type {number}
     * @memberof ServiceSetter
     */
    verify_status?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ServiceSetter
     */
    is_hot?: boolean;
}


