// tslint:disable
/**
 * 营销通
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ServiceConfigGetter
 */
export interface ServiceConfigGetter {
    /**
     * The current page number
     * @type {number}
     * @memberof ServiceConfigGetter
     */
    page: number;
    /**
     * The number of items per page
     * @type {number}
     * @memberof ServiceConfigGetter
     */
    size: number;
}


