// tslint:disable
/**
 * 营销通
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ServiceConfigData
 */
export interface ServiceConfigData {
    /**
     * 
     * @type {number}
     * @memberof ServiceConfigData
     */
    config_id: number;
    /**
     * 
     * @type {string}
     * @memberof ServiceConfigData
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceConfigData
     */
    image_url: string;
    /**
     * 
     * @type {number}
     * @memberof ServiceConfigData
     */
    contact_mobile?: number;
    /**
     * 
     * @type {string}
     * @memberof ServiceConfigData
     */
    create_time?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceConfigData
     */
    update_time?: string;
    /**
     * 
     * @type {number}
     * @memberof ServiceConfigData
     */
    type?: number;
    /**
     * 
     * @type {number}
     * @memberof ServiceConfigData
     */
    status?: number;
    /**
     * 
     * @type {string}
     * @memberof ServiceConfigData
     */
    create_by?: string;
}


