// tslint:disable
/**
 * 营销通
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { TagType } from './tag-type';

/**
 * 
 * @export
 * @interface TagDto
 */
export interface TagDto {
    /**
     * Semantic64<\"tag\">，The 64-bit hexadecimal string identifier
     * @type {string}
     * @memberof TagDto
     */
    tag_id: string;
    /**
     * 
     * @type {string}
     * @memberof TagDto
     */
    tag_name: string;
    /**
     * 
     * @type {TagType}
     * @memberof TagDto
     */
    tag_type: TagType;
    /**
     * Semantic64<\"tag\">，The 64-bit hexadecimal string identifier
     * @type {string}
     * @memberof TagDto
     */
    parent_id?: string;
    /**
     * 该字段总是空的!
     * @type {Array<TagDto>}
     * @memberof TagDto
     */
    children: Array<TagDto>;
    /**
     * Semantic64<\"user\">，The 64-bit hexadecimal string identifier
     * @type {string}
     * @memberof TagDto
     */
    created_user?: string;
    /**
     * Semantic64<\"user\">，The 64-bit hexadecimal string identifier
     * @type {string}
     * @memberof TagDto
     */
    updated_user?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TagDto
     */
    is_deleted: boolean;
}


