// tslint:disable
/**
 * 营销通
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { TagType } from './tag-type';

/**
 * 
 * @export
 * @interface TagQuery
 */
export interface TagQuery {
    /**
     * 
     * @type {TagType}
     * @memberof TagQuery
     */
    tag_type?: TagType;
    /**
     * The current page number
     * @type {number}
     * @memberof TagQuery
     */
    page: number;
    /**
     * The number of items per page
     * @type {number}
     * @memberof TagQuery
     */
    size: number;
}


