// tslint:disable
/**
 * 营销通
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserCount
 */
export interface UserCount {
    /**
     * 
     * @type {number}
     * @memberof UserCount
     */
    today_price: number;
    /**
     * 
     * @type {number}
     * @memberof UserCount
     */
    today_count: number;
    /**
     * 
     * @type {number}
     * @memberof UserCount
     */
    pro_price: number;
    /**
     * 
     * @type {number}
     * @memberof UserCount
     */
    pro_count: number;
    /**
     * 
     * @type {number}
     * @memberof UserCount
     */
    month_price: number;
    /**
     * 
     * @type {number}
     * @memberof UserCount
     */
    month_count: number;
    /**
     * 
     * @type {number}
     * @memberof UserCount
     */
    last_week_count: number;
    /**
     * 
     * @type {number}
     * @memberof UserCount
     */
    last_week_price: number;
    /**
     * 
     * @type {number}
     * @memberof UserCount
     */
    user_count: number;
    /**
     * 
     * @type {number}
     * @memberof UserCount
     */
    order_count: number;
    /**
     * 
     * @type {number}
     * @memberof UserCount
     */
    price_count: number;
    /**
     * 
     * @type {number}
     * @memberof UserCount
     */
    goods_count: number;
}


