// tslint:disable
/**
 * 营销通
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserQuery
 */
export interface UserQuery {
    /**
     * The current page number
     * @type {number}
     * @memberof UserQuery
     */
    page: number;
    /**
     * The number of items per page
     * @type {number}
     * @memberof UserQuery
     */
    size: number;
    /**
     * 注册时间范围
     * @type {string}
     * @memberof UserQuery
     */
    user_type?: string;
    /**
     * 
     * @type {number}
     * @memberof UserQuery
     */
    verify_status?: number;
    /**
     * 
     * @type {boolean}
     * @memberof UserQuery
     */
    is_admin?: boolean;
}


