// tslint:disable
/**
 * 营销通
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserSetter
 */
export interface UserSetter {
    /**
     * Semantic64<\"user\">，The 64-bit hexadecimal string identifier
     * @type {string}
     * @memberof UserSetter
     */
    user_id: string;
    /**
     * 
     * @type {string}
     * @memberof UserSetter
     */
    nick_name?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserSetter
     */
    is_marked?: boolean;
}


