// tslint:disable
/**
 * 营销通
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { BusinessType } from './business-type';
import { UserType } from './user-type';

/**
 * YxUser
 * @export
 * @interface UserItem
 */
export interface UserItem {
    /**
     * Semantic64<\"user\">，The 64-bit hexadecimal string identifier
     * @type {string}
     * @memberof UserItem
     */
    user_id: string;
    /**
     * 
     * @type {UserType}
     * @memberof UserItem
     */
    user_type: UserType;
    /**
     * 用户昵称
     * @type {string}
     * @memberof UserItem
     */
    nick_name: string;
    /**
     * 真实姓名
     * @type {string}
     * @memberof UserItem
     */
    real_name: string;
    /**
     * 
     * @type {string}
     * @memberof UserItem
     */
    company: string;
    /**
     * 
     * @type {string}
     * @memberof UserItem
     */
    create_time: string;
    /**
     * 
     * @type {BusinessType}
     * @memberof UserItem
     */
    business_type: BusinessType;
    /**
     * 
     * @type {number}
     * @memberof UserItem
     */
    verify_status: number;
}


