// tslint:disable
/**
 * 营销通
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserFeedback
 */
export interface UserFeedback {
    /**
     * 
     * @type {Array<string>}
     * @memberof UserFeedback
     */
    id_list: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof UserFeedback
     */
    feedback: string;
    /**
     * 
     * @type {number}
     * @memberof UserFeedback
     */
    verify_status: number;
}


