// tslint:disable
/**
 * 营销通
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * LoginParam
 * @export
 * @interface WechatLogin
 */
export interface WechatLogin {
    /**
     * 小程序登陆code
     * @type {string}
     * @memberof WechatLogin
     */
    login_code: string;
    /**
     * 
     * @type {string}
     * @memberof WechatLogin
     */
    phone_code?: string;
    /**
     * Semantic64<\"user\">，The 64-bit hexadecimal string identifier
     * @type {string}
     * @memberof WechatLogin
     */
    promotion_user?: string;
    /**
     * 
     * @type {string}
     * @memberof WechatLogin
     */
    promotion_code?: string;
}


