// tslint:disable
/**
 * 营销通
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WxUserResponse
 */
export interface WxUserResponse {
    /**
     * Semantic64<\"user\">，业务员 id
     * @type {string}
     * @memberof WxUserResponse
     */
    user_id: string;
    /**
     * 是否是新用户
     * @type {boolean}
     * @memberof WxUserResponse
     */
    user_new: boolean;
    /**
     * 微信 open_id
     * @type {string}
     * @memberof WxUserResponse
     */
    open_id: string;
    /**
     * 微信 union_id
     * @type {string}
     * @memberof WxUserResponse
     */
    union_id: string;
    /**
     * 微信 session_key
     * @type {string}
     * @memberof WxUserResponse
     */
    session_key: string;
    /**
     * 
     * @type {string}
     * @memberof WxUserResponse
     */
    access_token: string;
    /**
     * 
     * @type {string}
     * @memberof WxUserResponse
     */
    refresh_token: string;
}


